import { PrismaClient, ServiceType, ProviderStatus, ServiceStatus } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedPart16() {
  console.log('📦 Importando lote 16/16...');
  
  let providersCreated = 0;
  let servicesCreated = 0;
  let errors = 0;

  const providers = [
    {
      businessName: "Servicio automotriz Ferrer Talagante",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "(2) 2815 1224",
      email: "contacto16_0@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Calle - Leonardo Phillips 721, 9680202 Talagante, Región Metropolitana, Chile",
      latitude: -33.6593451,
      longitude: -70.9191367,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4.1,
      totalReviews: 233,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Serviteca Sánchez y Sánchez - Servicio automotriz y lubricentro",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "9 9505 0815",
      email: "contacto16_1@autolavado.cl",
      website: "",
      instagram: "None",
      address: "G-78 36, Talagante, Región Metropolitana, Chile",
      latitude: -33.6594116,
      longitude: -70.9171856,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4.7,
      totalReviews: 30,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Servicio Automotriz Silco Motors",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "9 5010 7079",
      email: "contacto16_2@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Lucas Pacheco 21, 9670000 Talagante, Región Metropolitana, Chile",
      latitude: -33.652427,
      longitude: -70.921476,
      city: "Talagante",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 1,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Casa Spa by Sandra Jimenez",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Talagante. Detailing Premium.",
      phone: "9 3504 0392",
      email: "contacto16_3@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. 21 de Mayo 962, 9670000 Talagante, Región Metropolitana, Chile",
      latitude: -33.6659805,
      longitude: -70.9290568,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4.9,
      totalReviews: 270,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Automotriz Labbe",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "(2) 2815 1766",
      email: "contacto16_4@autolavado.cl",
      website: "",
      instagram: "None",
      address: "República 665, 9680396 Talagante, Región Metropolitana, Chile",
      latitude: -33.6635411,
      longitude: -70.932503,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 75,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Mecánica automotriz Talagante",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_5@autolavado.cl",
      website: "https://www.facebook.com/talagantemecanica",
      instagram: "None",
      address: "Los Avellanos, 9670421 Talagante, Región Metropolitana, Chile",
      latitude: -33.6676074,
      longitude: -70.9281204,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 1,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Pintura automotriz S&S",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "9 3275 1604",
      email: "contacto16_6@autolavado.cl",
      website: "http://www.instagram.com/pintura_automotriz_sys",
      instagram: "http://www.instagram.com/pintura_automotriz_sys",
      address: "Av. Lonquén Sur 3528, Talagante, Región Metropolitana, Chile",
      latitude: -33.6800024,
      longitude: -70.8511284,
      city: "Talagante",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 1,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "MAS SC CHILE Aire Acondicionado Domiciliario y Automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Talagante. Lavado Tradicional.",
      phone: "9 7674 0316",
      email: "contacto16_7@autolavado.cl",
      website: "http://www.massc.cl/",
      instagram: "None",
      address: "Av. Bernardo O\'Higgins 225, 9670000 Talagante, Región Metropolitana, Chile",
      latitude: -33.6599633,
      longitude: -70.9189801,
      city: "Talagante",
      region: "Metropolitana",
      rating: 3.9,
      totalReviews: 11,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "House SPA",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Talagante. Detailing Premium.",
      phone: "9 9683 0752",
      email: "contacto16_8@autolavado.cl",
      website: "",
      instagram: "None",
      address: "el papagallo, Paradero 36 1/2, Talagante, Región Metropolitana, Chile",
      latitude: -33.6955324,
      longitude: -70.85099,
      city: "Talagante",
      region: "Metropolitana",
      rating: 4.7,
      totalReviews: 37,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Lavado LAVAMAX",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "9 6580 2645",
      email: "contacto16_9@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Los Libertadores 749, 9810371 El Monte, Región Metropolitana, Chile",
      latitude: -33.683278,
      longitude: -70.9940589,
      city: "El Monte",
      region: "Metropolitana",
      rating: 4.5,
      totalReviews: 10,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado de autos \"Donde Alejandro\"",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "9 2097 6775",
      email: "contacto16_10@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Los Libertadores 149, 9810251 El Monte, Región Metropolitana, Chile",
      latitude: -33.678591,
      longitude: -70.9773244,
      city: "El Monte",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado de autos hno abel",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "9 7415 6644",
      email: "contacto16_11@autolavado.cl",
      website: "https://wa.link/kmacqd",
      instagram: "None",
      address: "Domingo Sta. María 69, 9810370 El Monte, Región Metropolitana, Chile",
      latitude: -33.6816168,
      longitude: -70.99251339999999,
      city: "El Monte",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "lavado_carwash_",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_12@autolavado.cl",
      website: "https://www.instagram.com/lavado_carwash_/",
      instagram: "https://www.instagram.com/lavado_carwash_/",
      address: "San Miguel 640, Comuna, 9810569 El Monte, Región Metropolitana, Chile",
      latitude: -33.6747614,
      longitude: -70.9898063,
      city: "El Monte",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Limpicars",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_13@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Avenida - Los Libertadores 1556, 8500000 El Monte, Región Metropolitana, Chile",
      latitude: -33.6877742,
      longitude: -71.033703,
      city: "El Monte",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 10,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Los Chacon",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_14@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Llopeo, El Monte, Región Metropolitana, Chile",
      latitude: -33.6862647,
      longitude: -71.00270979999999,
      city: "El Monte",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Vincent Detail",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en El Monte. Lavado Tradicional.",
      phone: "9 7888 9668",
      email: "contacto16_15@autolavado.cl",
      website: "http://wa.me/56978889668",
      instagram: "None",
      address: "Once de Octubre 360, 9810169 El Monte, Región Metropolitana, Chile",
      latitude: -33.6793468,
      longitude: -70.99807899999999,
      city: "El Monte",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Zona lavados JRk jesurike",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_16@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Monte Grande 637, 9790235 Talagante, Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.7462557,
      longitude: -70.8985721,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "COPEC",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "800 200 354",
      email: "contacto16_17@autolavado.cl",
      website: "https://ww2.copec.cl/",
      instagram: "None",
      address: "Alcalde López N° 50, 9790170 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.7559845,
      longitude: -70.8973366,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.1,
      totalReviews: 215,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "PARISCAR.DETAILING",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Isla de Maipo. Detailing Premium.",
      phone: "9 4409 4323",
      email: "contacto16_18@autolavado.cl",
      website: "",
      instagram: "None",
      address: "El sauce - El Maitén 4456, 9800218 La Islita, Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.733647,
      longitude: -70.8656395,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Formula1impia",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "9 5416 5283",
      email: "contacto16_19@autolavado.cl",
      website: "",
      instagram: "None",
      address: "El Zaguán 257, 9790000 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.74448,
      longitude: -70.90088,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Chilexpress Agente Autorizado",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Isla de Maipo. Lavado Express.",
      phone: "+56912345678",
      email: "contacto16_20@autolavado.cl",
      website: "https://chilexpress.cl/",
      instagram: "None",
      address: "Av. Santelices 13, LOCAL B, 9790000 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.7560766,
      longitude: -70.8964847,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 51,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "BancoEstado - Sucursal Isla de Maipo",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "600 200 7000",
      email: "contacto16_21@autolavado.cl",
      website: "http://www.bancoestado.cl/",
      instagram: "None",
      address: "Av. Santelices 73, 9790170 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.75601,
      longitude: -70.89710099999999,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 2.2,
      totalReviews: 38,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Crematorio de Mascotas Las Nubes",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "9 3923 4982",
      email: "contacto16_22@autolavado.cl",
      website: "http://www.crematoriolasnubes.cl/",
      instagram: "None",
      address: "Santa ines 3683, 9790000 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.7413282,
      longitude: -70.8914528,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 1384,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "ISLACAR lubricentro",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Isla de Maipo. Lavado Tradicional.",
      phone: "9 7926 1436",
      email: "contacto16_23@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Santelices 1453, 9790258 Isla de Maipo, Región Metropolitana, Chile",
      latitude: -33.751026,
      longitude: -70.9100393,
      city: "Isla de Maipo",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 70,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Thekingcarwash",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_24@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Calle san Ignacio Sitio 5 manzana 6, 9710000 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5845545,
      longitude: -70.8087661,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.5,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado de Autos",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_25@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Primera Transversal 1092, 9710333 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.56727,
      longitude: -70.8009836,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "MOTOR SPOT - Hidromotor - Rubus Garage - Lubricentro",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 6870 4951",
      email: "contacto16_26@autolavado.cl",
      website: "https://www.motorspot.cl/",
      instagram: "None",
      address: "Cmo. a Melipilla 174, 9110000 Santiago, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5569624,
      longitude: -70.7992318,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.7,
      totalReviews: 18,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "COPEC",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "800 200 354",
      email: "contacto16_27@autolavado.cl",
      website: "https://ww2.copec.cl/",
      instagram: "None",
      address: "Cmo. a Melipilla N° 1891, 9720020 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5668635,
      longitude: -70.81268399999999,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.1,
      totalReviews: 591,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado De Papas",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_28@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Unnamed Road, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5555423,
      longitude: -70.82960779999999,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "B`ubble Car Spa",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Padre Hurtado. Detailing Premium.",
      phone: "9 7881 0605",
      email: "contacto16_29@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Ignacio Carrera Pinto 1104, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5686269,
      longitude: -70.79609359999999,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.7,
      totalReviews: 6,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Limpieza JL",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 5078 2955",
      email: "contacto16_30@autolavado.cl",
      website: "",
      instagram: "None",
      address: "España 211, 9710526 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5832505,
      longitude: -70.8138033,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Servicio técnico express",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Padre Hurtado. Lavado Express.",
      phone: "9 3090 5231",
      email: "contacto16_31@autolavado.cl",
      website: "https://www.instagram.com/lavatec_express?igsh=MWtibDE5MDh2MXpuNw==&utm_source=qr",
      instagram: "https://www.instagram.com/lavatec_express?igsh=MWtibDE5MDh2MXpuNw==&utm_source=qr",
      address: "Av. San Ignacio 1589, 9710000 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5617165,
      longitude: -70.82577119999999,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "Mr Jeff",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 2039 2066",
      email: "contacto16_32@autolavado.cl",
      website: "https://jeff.com/cl/mrjeff/store/padrehurtado-caminoamelipilla/?utm_source=localistico&utm_medium=localistico&utm_campaign=cl",
      instagram: "None",
      address: "Cmo. a Melipilla 2390, 9710140 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5693351,
      longitude: -70.8150039,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.8,
      totalReviews: 13,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Express de Lider",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Padre Hurtado. Lavado Express.",
      phone: "600 400 9000",
      email: "contacto16_33@autolavado.cl",
      website: "http://www.lider.cl/",
      instagram: "None",
      address: "Av. Primera Transversal 800, 9710300 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5653085,
      longitude: -70.7989642,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.9,
      totalReviews: 768,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "JC Clean Limpieza de alfombra",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 8310 0687",
      email: "contacto16_34@autolavado.cl",
      website: "https://wa.me/983100687",
      instagram: "None",
      address: "Rodolfo Jaramillo, 7970210 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5654285,
      longitude: -70.824316,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 18,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Express de Lider",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Padre Hurtado. Lavado Express.",
      phone: "600 400 9000",
      email: "contacto16_35@autolavado.cl",
      website: "http://www.lider.cl/tiendas",
      instagram: "None",
      address: "Laguna del Sol, Ex fundo - Las Compuertas, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5615121,
      longitude: -70.8276206,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.2,
      totalReviews: 3225,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "Chilexpress Agente Autorizado",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Padre Hurtado. Lavado Express.",
      phone: "+56912345678",
      email: "contacto16_36@autolavado.cl",
      website: "https://chilexpress.cl/",
      instagram: "None",
      address: "Cam. San Alberto Hurtado 1630, Local 9, 9710978 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5654549,
      longitude: -70.8099395,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.7,
      totalReviews: 41,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "Motel Amapola Padre Hurtado",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "(2) 2811 9679",
      email: "contacto16_37@autolavado.cl",
      website: "http://www.motelamapola.cl/",
      instagram: "None",
      address: "Tercera Avenida 193, 9710997 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5601196,
      longitude: -70.7993455,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 284,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Supermercado Tottus Padre Hurtado",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "600 329 2002",
      email: "contacto16_38@autolavado.cl",
      website: "https://www.tottus.cl/tottus-cl",
      instagram: "None",
      address: "Cmo. a Melipilla 2436, 9710000 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5718568,
      longitude: -70.8177942,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.9,
      totalReviews: 3826,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Motel Mi Sol",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 5514 3332",
      email: "contacto16_39@autolavado.cl",
      website: "http://www.motelmisol.cl/sitio",
      instagram: "None",
      address: "Tercera Avenida 1680, Maipú, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5687392,
      longitude: -70.7890681,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.3,
      totalReviews: 277,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Shinedry Estética Automotriz a Domicilio",
      businessType: "Lavado a Domicilio",
      description: "Autolavado profesional en Padre Hurtado. Lavado a Domicilio.",
      phone: "9 6461 6738",
      email: "contacto16_40@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Miraflores 2005, A-2, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.5992303,
      longitude: -70.8715505,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 6,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "OSG Automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 4595 3019",
      email: "contacto16_41@autolavado.cl",
      website: "https://www.osgautomotriz.cl/",
      instagram: "None",
      address: "Calle Sta. Isabel 1663, 9710983 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5665381,
      longitude: -70.8093091,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "ROMAN GARAGE",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 7146 4844",
      email: "contacto16_42@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Las Ñipas 10, 9710000 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5842056,
      longitude: -70.8177108,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 24,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lubricentro Matsa",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 3921 2833",
      email: "contacto16_43@autolavado.cl",
      website: "https://matsa.sivo.cl/",
      instagram: "None",
      address: "Cmo. a Melipilla, 9720139 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5724897,
      longitude: -70.8193548,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 4,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Nacar automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_44@autolavado.cl",
      website: "http://nacarautomotriz.cl/",
      instagram: "None",
      address: "Cmo. a Melipilla 1630, 9710000 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5648051,
      longitude: -70.8091302,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 21,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Full Serviteka",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_45@autolavado.cl",
      website: "",
      instagram: "None",
      address: "El Manzano 42, 9710979 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5663336,
      longitude: -70.8106449,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.4,
      totalReviews: 71,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Gsa automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_46@autolavado.cl",
      website: "http://www.servicioautomotrizgsa.cl/",
      instagram: "None",
      address: "Cmo. a Melipilla, 9710140 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5681672,
      longitude: -70.813098,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 4,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Salón de Belleza Integral KAIROS SpA",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Padre Hurtado. Detailing Premium.",
      phone: "9 9722 0604",
      email: "contacto16_47@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. San Ignacio 832, 9711132 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5674191,
      longitude: -70.8221874,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 121,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Aliena Motors",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 5089 9909",
      email: "contacto16_48@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Pje. Dieciocho 251, Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5915396,
      longitude: -70.8139231,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.9,
      totalReviews: 26,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Aire Acondicionado Automotriz Juan Cespedes",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 7681 0333",
      email: "contacto16_49@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Cmo. a Melipilla 2785, 9720131 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5718385,
      longitude: -70.81939299999999,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 101,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Freakycars",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 8951 3447",
      email: "contacto16_50@autolavado.cl",
      website: "http://www.freakycars.cl/",
      instagram: "None",
      address: "Av. Primera Transversal 1602, 9710071 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5699094,
      longitude: -70.8042431,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 3.5,
      totalReviews: 8,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Estética Casa & Energia",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Padre Hurtado. Lavado Tradicional.",
      phone: "9 9231 3744",
      email: "contacto16_51@autolavado.cl",
      website: "",
      instagram: "None",
      address: "villa valle del sol - Pje. Los Trigales 1582, 9711706 Padre Hurtado, Región Metropolitana, Chile",
      latitude: -33.5701529,
      longitude: -70.7915716,
      city: "Padre Hurtado",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 7,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Cars Vasquez",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 2095 6807",
      email: "contacto16_52@autolavado.cl",
      website: "http://carsvásquez.com/",
      instagram: "None",
      address: "21 de Mayo 3477, 9710030 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6055632,
      longitude: -70.8915901,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Fullpremiumwash",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "9 3377 7441",
      email: "contacto16_53@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Ottawa 956, 9273085 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.607875,
      longitude: -70.8663144,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Estacionamiento y Lavado de Autos Chalakos",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 5130 9617",
      email: "contacto16_54@autolavado.cl",
      website: "",
      instagram: "None",
      address: "José Miguel Carrera 57, 9750428 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6103163,
      longitude: -70.9024944,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 1,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "FullClean Lavaseco y Lavanderia",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "(2) 2891 6781",
      email: "contacto16_55@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Vicuña Mackenna 700, 9760353 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6103409,
      longitude: -70.8652922,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 25,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado de Autos Julito Videla",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_56@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Pje. Pica 3216, 9751236 Talagante, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6059189,
      longitude: -70.88877029999999,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavandería Los Andes",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_57@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Miraflores 936, local 5, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6013653,
      longitude: -70.8606118,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.8,
      totalReviews: 24,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "ShineZone",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_58@autolavado.cl",
      website: "https://instagram.com/shinezone.cl",
      instagram: "https://instagram.com/shinezone.cl",
      address: "Toribio Larraín 1715, 9810014 El Monte, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6151585,
      longitude: -70.86315019999999,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_59@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Sto Tomás 2023, 9750882 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6074273,
      longitude: -70.8809028,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Lavado de autos Gomez",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 9216 4707",
      email: "contacto16_60@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Las Encinas Nte. 162, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.61494,
      longitude: -70.863768,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 2,
      totalReviews: 2,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Chilexpress Full Service",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Peñaflor. Lavado Express.",
      phone: "+56912345678",
      email: "contacto16_61@autolavado.cl",
      website: "https://chilexpress.cl/",
      instagram: "None",
      address: "Larraín 3157, LOCAL B, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.5976281,
      longitude: -70.88491100000002,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "Chilexpress Agente Autorizado",
      businessType: "Lavado Express",
      description: "Autolavado profesional en Peñaflor. Lavado Express.",
      phone: "+56912345678",
      email: "contacto16_62@autolavado.cl",
      website: "https://chilexpress.cl/",
      instagram: "None",
      address: "Av. Miraflores 506, 9760472 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6020589,
      longitude: -70.85649060000001,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 3.7,
      totalReviews: 50,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Express", "type": "BASIC_WASH", "price": 5000, "duration": 15, "description": "Lavado r\u00e1pido"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}]
    },
    {
      businessName: "Morrison Steel",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 9251 3176",
      email: "contacto16_63@autolavado.cl",
      website: "http://www.morrisonsteel.cl/",
      instagram: "None",
      address: "95F5+FF, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6263056,
      longitude: -70.84125,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 6,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Taller automotriz Mym Asociados SpA",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "9 6715 9830",
      email: "contacto16_64@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Caupolicán 3590, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.5990603,
      longitude: -70.8880113,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 9,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Repuestos y Accesorios León Spa.",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "9 4280 9889",
      email: "contacto16_65@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Basterrica 045-A, 045-A, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6095792,
      longitude: -70.9004875,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 3.2,
      totalReviews: 40,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Aplicadora De Pinturas Industriales Y Automotriz Spa",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "+56912345678",
      email: "contacto16_66@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Santiago Arcos 2201, 9760844 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6070164,
      longitude: -70.8788119,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.0,
      totalReviews: 0,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Servicio Automotriz Settore",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 9743 9253",
      email: "contacto16_67@autolavado.cl",
      website: "https://www.settore.cl/",
      instagram: "None",
      address: "Av. Balmaceda 1876, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6170484,
      longitude: -70.8626824,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 32,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Mecánica Integral FJR.SPA",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "9 6107 3902",
      email: "contacto16_68@autolavado.cl",
      website: "https://www.fjrservigruas.cl/",
      instagram: "None",
      address: "C. Rosales Sur 1501, 9760677 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6046644,
      longitude: -70.8704547,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 1,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "Taller y Servicios Wolf",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_69@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. del Sol 1612, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.5990653,
      longitude: -70.84643980000001,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 3,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Spa Natura Mallinco",
      businessType: "Detailing Premium",
      description: "Autolavado profesional en Peñaflor. Detailing Premium.",
      phone: "9 7874 7393",
      email: "contacto16_70@autolavado.cl",
      website: "",
      instagram: "None",
      address: "El Muelle, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.5910051,
      longitude: -70.88303909999999,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.3,
      totalReviews: 742,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Detailing Completo", "type": "DETAILING", "price": 45000, "duration": 180, "description": "Servicio completo de detailing"}, {"name": "Pulido y Encerado", "type": "WAXING", "price": 25000, "duration": 90, "description": "Pulido profesional"}, {"name": "Sellado Cer\u00e1mico", "type": "CERAMIC_COATING", "price": 80000, "duration": 240, "description": "Protecci\u00f3n cer\u00e1mica"}]
    },
    {
      businessName: "NicoGarage",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 7642 1150",
      email: "contacto16_71@autolavado.cl",
      website: "https://www.instagram.com/nicogarage.cl/profilecard/?igsh=MTdvZHI0OWZ5aG43bQ==",
      instagram: "https://www.instagram.com/nicogarage.cl/profilecard/?igsh=MTdvZHI0OWZ5aG43bQ==",
      address: "Av. Peñaflor 3600, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6333498,
      longitude: -70.9103684,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.8,
      totalReviews: 80,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Luce Servicio Automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 6871 4519",
      email: "contacto16_72@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Berlín 42-5, Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6295675,
      longitude: -70.907795,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 5,
      totalReviews: 3,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Taller De Mantenciones Y Pintura Automotriz",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "+56912345678",
      email: "contacto16_73@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Lo Márquez 0865, 9750772 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.60680910000001,
      longitude: -70.8929145,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4.6,
      totalReviews: 8,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
    {
      businessName: "Memphis Auto Motors",
      businessType: "Lavado Tradicional",
      description: "Autolavado profesional en Peñaflor. Lavado Tradicional.",
      phone: "9 4039 6862",
      email: "contacto16_74@autolavado.cl",
      website: "",
      instagram: "None",
      address: "Av. Peñaflor 3600, 9750000 Penaflor, Peñaflor, Región Metropolitana, Chile",
      latitude: -33.6296522,
      longitude: -70.9090196,
      city: "Peñaflor",
      region: "Metropolitana",
      rating: 4,
      totalReviews: 4,
      services: [{"name": "Lavado Exterior Completo", "type": "BASIC_WASH", "price": 8000, "duration": 30, "description": "Lavado completo del exterior del veh\u00edculo"}, {"name": "Lavado Interior", "type": "INTERIOR_CLEAN", "price": 12000, "duration": 45, "description": "Limpieza profunda interior"}, {"name": "Lavado Completo", "type": "PREMIUM_WASH", "price": 18000, "duration": 60, "description": "Exterior + Interior"}, {"name": "Lavado de Motor", "type": "ENGINE_CLEAN", "price": 10000, "duration": 30, "description": "Limpieza de motor"}]
    },
  ];

  for (const providerData of providers) {
    try {
      const provider = await prisma.provider.create({
        data: {
          businessName: providerData.businessName,
          businessType: providerData.businessType,
          description: providerData.description,
          status: ProviderStatus.ACTIVE,
          phone: providerData.phone,
          email: providerData.email,
          website: providerData.website,
          instagram: providerData.instagram,
          address: providerData.address,
          latitude: providerData.latitude,
          longitude: providerData.longitude,
          city: providerData.city,
          region: providerData.region,
          postalCode: '7500000',
          rating: providerData.rating,
          totalReviews: providerData.totalReviews,
          isImported: true,
          operatingHours: {
            monday: { open: '09:00', close: '19:00' },
            tuesday: { open: '09:00', close: '19:00' },
            wednesday: { open: '09:00', close: '19:00' },
            thursday: { open: '09:00', close: '19:00' },
            friday: { open: '09:00', close: '20:00' },
            saturday: { open: '09:00', close: '18:00' },
            sunday: { open: '10:00', close: '16:00' },
          },
          verifiedAt: new Date(),
        },
      });
      providersCreated++;

      // Crear servicios
      for (const [index, serviceData] of providerData.services.entries()) {
        await prisma.service.create({
          data: {
            providerId: provider.id,
            name: serviceData.name,
            description: serviceData.description,
            type: ServiceType[serviceData.type as keyof typeof ServiceType],
            status: ServiceStatus.ACTIVE,
            price: serviceData.price,
            duration: serviceData.duration,
            currency: 'CLP',
            isAvailable: true,
            isFeatured: index === 0,
            displayOrder: index,
          },
        });
        servicesCreated++;
      }
    } catch (error: any) {
      console.error(`Error: ${error.message.substring(0, 50)}...`);
      errors++;
    }
  }

  console.log(`✅ Lote {chunk_num}: ${providersCreated} proveedores, ${servicesCreated} servicios (${errors} errores)`);
  
  return { providersCreated, servicesCreated, errors };
}
